-- Company table
CREATE TABLE company (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255),
    founded INTEGER
);

INSERT INTO COMPANY (NAME, FOUNDED) VALUES ('XYZ Corp', 1995)