spring:
  output:
    ansi:
      enabled: always
camel:
  component:
    kafka:
      enabled: false
    http:
      enabled: false
    scheduler:
      enabled: false

gateway:
  type: "http-poll-kafka"
main-scheduler:
  endpoint-properties:
    delay: "1000"
rest-poll:
  host: "nginx-poll"
  resource-path: "salary"
  port: "80"
  endpoint-properties:
    httpMethod: "GET"
kafka-out:
  brokers: "kafka:9092"
  topic: "routetest"
