spring:
  output:
    ansi:
      enabled: always
camel:
  component:
    kafka:
      enabled: false
    http:
      enabled: false
    scheduler:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

gateway:
  type: "http-poll-kafka"
redelivery-policy:
  maximum-redeliveries: 2
  redelivery-delay: 100
  retry-attempted-log-level: "WARN"
error-handler:
  redelivery-policy-ref: "redelivery-policy"
main-scheduler:
  endpoint-properties:
    delay: "1000"
rest-poll:
  host: "nginx-poll"
  resource-path: "salary"
  port: "80"
  endpoint-properties:
    httpMethod: "GET"
kafka-out:
  brokers: "kafka:9092"
  topic: "routetest"
