spring:
  output:
    ansi:
      enabled: always
camel:
  component:
    kafka:
      enabled: false
    http:
      enabled: false
    servlet:
      enabled: false
    rest:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

gateway:
  type: "http-kafka"
error-handler:
  redelivery-policy:
    maximum-redeliveries: 2
    redelivery-delay: 100
rest-in:
  clientRequestValidation: "true"
  component: "servlet"
  routes:
    -
      path: "/api"
      consumes: "text/plain"
      produces: "text/plain"
      httpMethod: "POST"
      id: "rest-in"
      to:
        uri: "direct:process"
kafka-out:
  brokers: "kafka:9092"
  topic: "routetest"
  delivery-timeout-ms: 1000
  request-timeout-ms: 500
  max-block-ms: 1000
