spring:
  output:
    ansi:
      enabled: always
camel:
  component:
    kafka:
      enabled: false
    http:
      enabled: false
    servlet:
      enabled: false
    rest:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

gateway:
  type: "http-kafka"
rest-in:
  clientRequestValidation: "true"
  component: "servlet"
  routes:
    -
      path: "/api"
      consumes: "text/plain"
      produces: "text/plain"
      httpMethod: "POST"
      id: "rest-in"
      to:
        uri: "direct:process"
kafka-out:
  brokers: "kafka:9092"
  topic: "routetest"
