spring:
  output:
    ansi:
      enabled: always
camel:
  component:
    kafka:
      enabled: false
    http:
      enabled: false
    scheduler:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

gateway:
  type: "http-poll-http"
main-scheduler:
  endpoint-properties:
    delay: "1000"
rest-poll:
  host: "nginx-poll"
  resource-path: "salary"
  port: "80"
  endpoint-properties:
    httpMethod: "GET"
rest-call:
  host: "nginx-call"
  resource-path: "person"
  port: "80"
  endpoint-properties:
    httpMethod: "POST"
