spring:
  output:
    ansi:
      enabled: always
camel:
  component:
    kafka:
      enabled: false
    http:
      enabled: false
    scheduler:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

gateway:
  type: "kafka-http"
kafka-in:
  brokers: "kafka:9092"
  topic: "routetest_request"
  consumers-count: 3
  group-id: "KAFKA_HTTP_KAFKA_FIRST_TESTING6"
  break-on-error: false
  auto-offset-reset: "earliest"
  max-poll-records: 500
  max-partition-fetch-bytes: 1048576
  heartbeat-interval-ms: 3000
  session-timeout-ms: 10000
rest-call:
  host: "nginx-call"
  resource-path: "person"
  port: "80"
  endpoint-properties:
    httpMethod: "POST"
