spring:
  output:
    ansi:
      enabled: always
camel:
  component:
    kafka:
      enabled: false
    http:
      enabled: false
    scheduler:
      enabled: false
    freemarker:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

gateway:
  type: "scheduler-kafka"
redelivery-policy:
  maximum-redeliveries: 2
  redelivery-delay: 1000
  retry-attempted-log-level: "WARN"
error-handler:
  redelivery-policy-ref: "redelivery-policy"
main-scheduler:
  poolSize: "1"
  endpoint-properties:
    delay: "1000"
processing:
  after-consumer:
    transform:
      resource-uri: "file://app/load.tmpl"
kafka-out:
  brokers: "kafka:9092"
  topic: "routetest_request"
