version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - gateway-network

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    ports:
      - '9092:9092'
      - '19092:19092' # Внешний порт для доступа с хоста
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:19092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - gateway-network

  kafka-topic:
    image: confluentinc/cp-kafka:6.2.1
    depends_on:
      - kafka
    command: >
      bash -c "sleep 10 &&
      kafka-topics --create --topic routetest --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092"
    restart: "no"
    networks:
      - gateway-network

  gateway:
    image: bridle-gateway:latest
    build: ../.
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '1'
    environment:
      - SPRING_CONFIG=/app/config/application.yml
    volumes:
      - ./configs/http-kafka/application.yml:/app/config/application.yml
    depends_on:
      - kafka-topic
    networks:
      - gateway-network

  load-generator:
    image: bridle-gateway:latest
    build: ../.
    environment:
      - SPRING_CONFIG=/app/config/application.yml
      - MAIN-SCHEDULER_ENDPOINT-PROPERTIES_DElAY=1000
    volumes:
      - ./configs/load-freemarker-http/application.yml:/app/config/application.yml
      - ./configs/load-freemarker-http/load.tmpl:/app/load.tmpl
    depends_on:
      - gateway
    networks:
      - gateway-network

networks:
  gateway-network:
