version: '3'

services:

  nginx-poll:
    image: nginx:latest
    ports:
      - '80'
    volumes:
      - ./configs/http-poll-http/nginx-poll.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gateway-network

  nginx-call:
    image: nginx:latest
    ports:
      - '80'
    volumes:
      - ./configs/http-poll-http/nginx-call.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gateway-network

  gateway:
    image: bridle-gateway:latest
    build: ../.
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '1'
    environment:
      - SPRING_CONFIG=/app/config/application.yml
    volumes:
      - ./configs/http-poll-http/application.yml:/app/config/application.yml
    depends_on:
      - nginx-call
      - nginx-poll
    networks:
      - gateway-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./configs/metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - gateway
    networks:
      - gateway-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/metrics/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./configs/metrics/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    networks:
      - gateway-network

volumes:
  grafana_data: {}

networks:
  gateway-network:
