version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx-poll.conf:/etc/nginx/nginx.conf:ro

  gateway:
    image: bridle-gateway:latest
    build: ../.
    environment:
      - SPRING_CONFIG=/app/config/application.yml
    volumes:
      - ./configs/http-kafka/application.yml:/app/config/application.yml
    depends_on:
      - kafka-topic
    networks:
      - gateway-network

  load-generator:
    image: bridle-gateway:latest
    build: ../.
    environment:
      - SPRING_CONFIG=/app/config/application.yml
      - MAIN-SCHEDULER_ENDPOINT-PROPERTIES_DElAY=20
    volumes:
      - ./configs/load-freemarker-http/application.yml:/app/config/application.yml
      - ./configs/load-freemarker-http/load.tmpl:/app/load.tmpl
    depends_on:
      - gateway
    networks:
      - gateway-network

networks:
  gateway-network:
